import { AsideMenu } from "@/widgets";
import type { Metadata } from "next";
import styles from './layout.module.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={styles.container}>
      <AsideMenu />
      {children}
    </main>
  );
}
