export const ProjectsData = [
  {
    id: 1,
    userId: 1,
    status: "To do",
    project: "Design system",
    title: "Design new ui presentation",
    subtitle: "Dribbble marketing",
    description: "Design new ui presentation",
    totalTasks: 10,
    completedTasks: 7,
    comments: 7,
    files: 2,
    time: "2024-05-07",
  },
  {
    id: 2,
    userId: 1,
    status: "To do",
    project: "Design system",
    title: "Add more ui/ux mockups",
    subtitle: "Pinterest promotion",
    description: "Add more ui/ux mockups",
    totalTasks: 10,
    completedTasks: 4,
    comments: 7,
    files: 2,
    time: "2024-24-06",
  },
  {
    id: 3,
    userId: 1,
    status: "To do",
    project: "Design system",
    title: "Design few mobile screens",
    subtitle: "Dropbox mobile app",
    description: "Design few mobile screens",
    totalTasks: 10,
    completedTasks: 3,
    comments: 6,
    files: 4,
    time: "2024-30-06",
  },
  {
    id: 4,
    userId: 1,
    status: "To do",
    project: "Design system",
    title: "Create a tweet and promote",
    subtitle: "Twitter marketing",
    description: "Create a tweet and promote",
    totalTasks: 14,
    completedTasks: 2,
    comments: 7,
    files: 2,
    time: "2024-27-07",
  },
  {
    id: 5,
    userId: 1,
    status: "In progress",
    project: "Design system",
    title: "Design new ui presentation",
    subtitle: "Dribbble marketing",
    description: "Design new ui presentation",
    totalTasks: 10,
    completedTasks: 7,
    comments: 7,
    files: 2,
    time: "2024-05-07",
  },
  {
    id: 6,
    userId: 1,
    status: "In progress",
    project: "Design system",
    title: "Design new ui presentation",
    subtitle: "Dribbble marketing",
    description: "Design new ui presentation",
    totalTasks: 10,
    completedTasks: 7,
    comments: 7,
    files: 2,
    time: "2024-05-07",
  },
  {
    id: 7,
    userId: 1,
    status: "In progress",
    project: "Design system",
    title: "Design new ui presentation",
    subtitle: "Dribbble marketing",
    description: "Design new ui presentation",
    totalTasks: 10,
    completedTasks: 7,
    comments: 7,
    files: 2,
    time: "2024-05-07",
  },
  {
    id: 8,
    userId: 1,
    status: "In progress",
    project: "Design system",
    title: "Design new ui presentation",
    subtitle: "Dribbble marketing",
    description: "Design new ui presentation",
    totalTasks: 10,
    completedTasks: 7,
    comments: 7,
    files: 2,
    time: "2024-05-07",
  },
  {
    id: 9,
    userId: 1,
    status: "Done",
    project: "Design system",
    title: "Design new ui presentation",
    subtitle: "Dribbble marketing",
    description: "Design new ui presentation",
    totalTasks: 10,
    completedTasks: 10,
    comments: 9,
    files: 3,
    time: "2024-05-07",
  },
  {
    id: 10,
    userId: 1,
    status: "Done",
    project: "Design system",
    title: "Design new ui presentation",
    subtitle: "Dribbble marketing",
    description: "Design new ui presentation",
    totalTasks: 10,
    completedTasks: 10,
    comments: 21,
    files: 15,
    time: "2024-05-07",
  },
  {
    id: 11,
    userId: 1,
    status: "Done",
    project: "Design system",
    title: "Design new ui presentation",
    subtitle: "Dribbble marketing",
    description: "Design new ui presentation",
    totalTasks: 10,
    completedTasks: 10,
    comments: 121,
    files: 12,
    time: "2024-05-07",
  },
  {
    id: 12,
    userId: 1,
    status: "Done",
    project: "User flow",
    title: "Design new ui presentation",
    subtitle: "Dribbble marketing",
    description: "Design new ui presentation",
    totalTasks: 10,
    completedTasks: 10,
    comments: 121,
    files: 12,
    time: "2024-05-07",
  },
  {
    id: 13,
    userId: 1,
    status: "In progress",
    project: "Ux research",
    title: "Design new ui presentation",
    subtitle: "Dribbble marketing",
    description: "Design new ui presentation",
    totalTasks: 7,
    completedTasks: 10,
    comments: 1,
    files: 4,
    time: "2024-05-07",
  },
];